#!/bin/sh -e
# =============================================================================
# rootfs 子模块: 写入 deviceinfo (boot-deploy / mkinitfs 的依据)
# 必须先于内核安装存在, 因为安装内核时 mkinitfs 触发器会立即运行
# =============================================================================

HERE="$(cd "$(dirname "$0")" && pwd)"
. "${HERE}/../lib/common.sh"

log "Writing deviceinfo..."

mkdir -p "${CHROOT}/usr/share/deviceinfo"
cat > "${CHROOT}/usr/share/deviceinfo/deviceinfo" <<EOF
# OpenStick deviceinfo (generated by pmos_rootfs.sh)
deviceinfo_format_version="0"
deviceinfo_name="OpenStick ${BOARD}"
deviceinfo_manufacturer="Generic"
deviceinfo_codename="openstick-${BOARD}"
deviceinfo_arch="aarch64"

# Device related (headless dongle, no screen)
deviceinfo_chassis="embedded"
deviceinfo_keyboard="false"
deviceinfo_external_storage="false"
deviceinfo_no_framebuffer="true"
deviceinfo_getty="ttyMSM0;115200"

# Bootloader related
deviceinfo_flash_method="fastboot"
deviceinfo_kernel_cmdline="earlycon console=ttyMSM0,115200 rw rootwait"
deviceinfo_dtb="${DTB}"
deviceinfo_append_dtb="true"
deviceinfo_generate_extlinux_config="true"
deviceinfo_boot_filesystem="ext2"
deviceinfo_partition_type="gpt"
EOF
